attendees/urls.py
from django.conf.urls import url

from .views import register_attendee

urlpatterns = [

    url(r'^register/', register_attendee, name='register'),
]

events/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^blogs/', include('shows.urls', namespace='shows')),
    url(r'^attendees/', include('attendees.urls', namespace='attendees')),
]

shows/urls.py
from django.conf.urls import url, include

from .views import show_list, show_create

urlpatterns = [

    url(r'^list/', show_list, name='list'),
    url(r'^create/', show_create, name='create'),
]

attendees/models.py
from django.db import models

from shows.models import Show


# Create your models here.

class Attendee(models.Model):
    show = models.ForeignKey(Show)
    name = models.CharField(max_length=40)
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

shows/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Show(models.Model):
    title = models.CharField(max_length=160)
    description = models.TextField()
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

attendees/forms.py
from django.forms import ModelForm

from .models import Attendee


class AttendeeForm(ModelForm):
    class Meta:
        model = Attendee
        fields = [
            'name',
            'email',
        ]

shows/forms.py
from django.forms import ModelForm

from .models import Show

class ShowForm(ModelForm):
    class Meta:
        model = Show
        fields = (
            'title',
            'description'
        )

attendees/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

from .models import Attendee
from shows.models import Show
from .forms import AttendeeForm

# Create your views here.


def register_attendee(request, pk=None):
    if request.method == 'GET':
        pk = request.GET.get('pk')
        show = Show.objects.get(pk=pk)

    if request.method == 'POST':
        pk = request.POST.get('pk')
        show = Show.objects.get(pk=pk)
        form = AttendeeForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.show = show
            subject = 'Congrats! you are successfully registered for ' + show.title
            message = 'Hi' + instance.name + '\nYou have successfully registered for ' + show.title + '\n \nThank you for using our application. \nDo come again.\nSupport: care@myapp.com'
            send_mail(subject, message, 'you_gmail_id', [instance.email])
            instance.save()
            return HttpResponseRedirect('/')
    else:
        form = AttendeeForm()

    context = {
        'object': show,
        'form': form
    }

    return render(request, 'attendees/register.html', context)

shows/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

from .models import Show
from .forms import ShowForm

# Create your views here.


def show_list(request):
    object_list = Show.objects.all()
    context = {
        'object_list': object_list
    }

    return render(request, 'shows/list.html', context)


def show_create(request):
    if request.method == 'POST':

        form = ShowForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return HttpResponseRedirect('/')

    else:
        form = ShowForm()

    context = {
        'form': form,
    }

    return render(request, 'shows/create.html', context)

templates/attendees/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="s6">
                <h4>{{ object.title }}</h4>
                <p>{{ object.description }}</p>
            </div>
            <div class="s6">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="hidden" name="pk" id="pk" value="{{ object.pk }}">
                    <input type="submit" class="btn" value="Confirm Booking" {{disabled}}>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Blog App{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">

    <link type="text/css" rel="stylesheet" href="css/style.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


</head>

<body>

<nav>
    <div class="nav-wrapper teal lighten-2">
        <a href="#" class="brand-logo">Event App</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
{#            {% if request.user.is_authenticated %}#}
{#            <li><a href="#">{{ request.user.username }}</a></li>#}
            <li><a href="{% url 'shows:list' %}">List Events</a></li>
{#            {% else %}#}
{#            <li><a href="{% url 'account_login' %}">Login</a></li>#}
{#                <li><a href="{% url 'account_signup' %}">Sign Up</a></li>#}
{#            {% endif %}#}
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}



<br><br><br><br><br>
<footer class="page-footer teal lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer
                    content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>


<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</body>
</html>

templates/shows/create.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
        <input type="submit" value="Create Show">
    </form>


{% endblock %}

templates/shows/list.html
{% extends 'base.html' %}

{% block content %}
    {% if object_list %}

            <div class="container">
                {% for object in object_list %}
                <div class="row">
                    <div class="s6">
                        <h4>
                            {{ object.title }}
                        </h4>
                    </div>
                    <div class="s6">
                        {{ object.description }}
                    </div>
                    <form action="{% url 'attendees:register' %}" method="get">
                        {%  csrf_token %}
                        <input type="hidden" name="pk" id="pk" value="{{ object.pk }}">
                        <input type="submit" class="btn" value="Book This Movie">
                    </form>
                </div>
            {% endfor %}
            </div>


    {% endif %}


{% endblock %}